name: My qa-CICD.yml
on:
  push:
    branches: [ "qa" ] 
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-CICD.yml
   

jobs:
  gitleaks-scan:  #the Job ID for gitleaks
    name: GitLeaks Scan  # name of the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code  # the first step is to clone the repo into the vm
        uses: actions/checkout@v4  #the official GitHub Action used to clone and download your Git repository into a GitHub Actions runner environment


      - name: Run Gitleaks Scan  #next step
        run: |  #run shell commands
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \      # mounts repo into the container
            zricethezav/gitleaks:latest detect \
            --source=/repo \
            --report-format=json \      # outputs results as JSON
            --report-path=/repo/gitleaks-report.json \
            --redact \                  # masks secret values in the report
            --exit-code 0               # always exits 0 (won't fail the pipeline)
        
       
      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          if-no-files-found: warn
 
